Added file number images to status page
DTS-STN/passport-status pull request #175
Opened 2022-12-09 21:55 UTC by Maxim-Lam

## [ADO-XXX](https://dev.azure.com/DTS-STN/passport-status/_workitems/edit/xxx)

### Description

List of proposed changes:

Added images under an expand/collapse component. 

I think Design systems describes collapse widgets use the best:
![image](https://user-images.githubusercontent.com/109530511/206802084-dca78a36-da32-43a1-9de9-79a53f8ab479.png)

### What to test for/How to test

navigate to /status

toggle collapse in both french and english

### Additional Notes

2022-12-12 19:39 UTC, krischarbonneau requested changes

2022-12-12 19:39 UTC, krischarbonneau commented on components/Collapse.tsx
> +      <summary className="text-blue-light">{title}</summary>
```suggestion
      <summary className="text-blue-light hover:underline hover:text-link-selected cursor-pointer focus:text-link-selected focus:underline">{title}</summary>
```

Following the design seen [here](https://design.canada.ca/common-design-patterns/collapsible-content.html), there should be hover and focus styling on the summary element

2022-12-12 23:15 UTC, sebastien-comeau reviewed
Minor tweak and to fix the failing status page tests you need to mock ExampleImage component.
```js
jest.mock('../../components/ExampleImage')
```

2022-12-12 23:15 UTC, sebastien-comeau commented on components/Collapse.tsx
> +  children?: JSX.Element
Should be the following type:

```tsx
children?: React.ReactNode
```

2022-12-13 11:24 UTC, sebastien-comeau commented
My only concern is accessibility. I wonder if the details or summary element should have an id and the input have this id in his aria-describedby attribute. I've searched for this information but didn't find any good info with details/summary element.

2022-12-13 14:47 UTC, Maxim-Lam commented
> My only concern is accessibility. I wonder if the details or summary element should have an id and the input have this id in his aria-describedby attribute. I've searched for this information but didn't find any good info with details/summary element.

I have added an aria-describeby as you suggested. Let me know if there is anything else

2022-12-13 16:52 UTC, krischarbonneau approved these changes
Looks good!

2022-12-13 16:56 UTC, merged